# Generated by Django 5.0.3 on 2024-04-03 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_subscription_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'post', 'favorite_collection')},
        ),
        migrations.AlterUniqueTogether(
            name='favoritecollection',
            unique_together={('user', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
